language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - build-tools-26.0.2
    - android-25

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # No emulator - for now